language: ruby
sudo: false

rvm:
  - 2.2.3

services: [ redis ]

branches:
  only:
    - master

before_script:
  - 'RAILS_ENV=test bundle exec rake db:create'
  # - psql -c 'create database podfilter_test' -U postgres
  - cp config/database.yml.travis config/database.yml
  - "bundle exec rake db:schema:load RAILS_ENV=test"

script:
  - bundle exec rspec

bundler_args: "--without development production"
